case $CONFIG in
'')
	if test ! -f ../config.sh; then
		(echo "Can't find ../config.sh."; exit 1)
	fi 2>/dev/null
	. ../config.sh
	;;
esac
case "$O" in
*/*) cd `expr X$0 : 'X\(.*\)/'` ;;
esac
echo "Compiling C code in C2"
$spitshell >Makefile <<!GROK!THIS!
INCLUDE_PATH =  -I"\$(IRON_PATH)\packages\game\C_lib_win\OpenAL\include" -I"\$(IRON_PATH)/packages/game/cpf_lib/spec/include" -I"\$(IRON_PATH)/packages/game/audio_snd_files_lib/spec/include" -I"\$(IRON_PATH)\packages\game\C_lib_win\libsndfile\include" -I"\$(IRON_PATH)/packages/game/game_core_lib/spec/include" -I"\$(IRON_PATH)\packages\game\C_lib_win\SDL\include" -I"\$(IRON_PATH)\packages\game\C_lib_win\SDL_gfx\include" -I"\$(IRON_PATH)\packages\game\C_lib_win\SDL_image\include" -I"\$(IRON_PATH)\packages\game\C_lib_win\SDL_ttf\include"
SHELL = /bin/sh
CC = $cc
CPP = $cpp
CFLAGS = $wkoptimize $mtccflags $large -DEIF_IEEE_BEHAVIOR -DWORKBENCH -I"$rt_include" -I. \$(INCLUDE_PATH)
CPPFLAGS = $wkoptimize $mtcppflags $large -DWORKBENCH -I"$rt_include" -I. \$(INCLUDE_PATH)
LDFLAGS = $ldflags
CCLDFLAGS = $ccldflags  $console_flags
LDSHAREDFLAGS =  $mtldsharedflags
EIFLIB = "$rt_lib/$prefix$mt_prefix$wkeiflib$suffix"
EIFTEMPLATES = $rt_templates
LIBS = $mtlibs
MAKE = $make
AR = $ar
LD = $ld
MKDEP = $mkdep \$(DPFLAGS) --
MV = $mv
CP = $cp
RANLIB = $ranlib
RM = $rm -f
FILE_EXIST = $file_exist
RMDIR = $rmdir
X2C = "$x2c"
SHAREDLINK = $sharedlink
SHAREDLIBS = $sharedlibs
SHARED_SUFFIX = $shared_suffix
COMMAND_MAKEFILE = 
START_TEST = $start_test 
END_TEST = $end_test 
CREATE_TEST = $create_test 
SYSTEM_IN_DYNAMIC_LIB = project$shared_suffix 
!GROK!THIS!
$spitshell >>Makefile <<'!NO!SUBS!'

.SUFFIXES:.cpp .o

.c.o:
	$(CC) $(CFLAGS) -c $<

.cpp.o:
	$(CPP) $(CPPFLAGS) -c $<

OBJECTS = big_file_C2_c.obj 

OLDOBJECTS =  ap922.o ap922d.o au902.o au902d.o au906.o au906d.o au901.o au901d.o \
	th896.o th896d.o le900.o le900d.o ma899.o ma899d.o op898.o op898d.o \
	ga912.o ga912d.o ga917.o ga917d.o ga916.o ga916d.o ga915.o ga915d.o \
	th894.o th894d.o au905.o au905d.o au903.o au903d.o th895.o th895d.o \
	te921.o te921d.o dr919.o dr919d.o ba897.o ba897d.o au904.o au904d.o \
	ga914.o ga914d.o ga893.o ga893d.o ti910.o ti910d.o ab911.o ab911d.o \
	ga913.o ga913d.o pe920.o pe920d.o ga918.o ga918d.o du907.o du907d.o \
	da924.o da924d.o ga925.o ga925d.o da909.o da909d.o da908.o da908d.o \
	da923.o da923d.o 

all: Cobj2.o

Cobj2.o: $(OBJECTS) Makefile
	$(LD) $(LDFLAGS) -r -o Cobj2.o $(OBJECTS)
	$(RM) $(OBJECTS)
	$(CREATE_TEST)

clean: local_clean
clobber: local_clobber

local_clean::
	$(RM) core finished *.o

local_clobber:: local_clean
	$(RM) Makefile

!NO!SUBS!
chmod 644 Makefile
$eunicefix Makefile

